version: '3.8'
services:
  exchange-service:
    image: exchange-service:latest
    build:
      context: ./exchange
    deploy:
      replicas: 2
    networks:
      - app-network
    expose:
      - "8080"  

  fidelity-service:
    image: fidelity-service:latest
    build:
      context: ./fidelity
    ports:
      - "8081:8080"
    networks:
      - app-network
    expose:
      - "8080"

  store-service:
    image: store-service:latest
    build:
      context: ./store
    ports:
      - "8082:8080"
    networks:
      - app-network
    expose:
      - "8080"

  nginx:
    image: nginx:latest        
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  
    ports:
      - "8080:80"                  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
