version: '3.8'
services:
  exchange-service:
    image: exchange-service:latest
    deploy:
      replicas: 2
    networks:
      - app-network
    expose:
      - "8080"                    

  nginx:
    image: nginx:latest        
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  
    ports:
      - "8080:80"                  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
